### ISSUE TITLE
MMAudio nodes missing

### ISSUE THREAD

**Issue by tridhe** [kijai/ComfyUI-MMAudio#10]
Do I need to install any custom nodes other than the video helper suite? Because I am getting missing nodes when I load the workflow. I have already cloned and installed form the github repo. What could be the issue?

Error:
Missing Node Types
When loading the graph, the following node types were not found

MMAudioSampler
MMAudioFeatureUtilsLoader
MMAudioModelLoader

**Comment by kijai** [comment]
Those are the nodes from this repo, check your comfy startup log for any import errors to find out what could be missing, could also be a version mismatch of some dependency.

**Comment by tridhe** [comment]
You were right. The following dependencies were missing. I am not sure why it was not installed, even though the pip install command ran successfully. Now the issue is resolved. thanks
librosa>=0.10.1
torchdiffeq>=0.2.3
omegaconf>=2.3.0

**Comment by skpManiac** [comment]
Hi guys, I have this exact issue. 
I have downloaded all the packages needed and put them in the mmaudio folders /nvidia etc but still get the same error.
How did you install the fix? 
I tried the PIP install but that fails :( 

Thank you for any help :)
